### ISSUE TITLE
Load CSV files

### ISSUE THREAD

**Issue by sergiofenoll** [sergiofenoll/project-databases#8]
Part of the base implementation is loading in CSV files to be used as raw data by the data cleaning app.

**Comment by MeyerJon** [comment]
Creating tables from CSV files is possible via the DataLoader class. 
Appending data isn't possible yet, though. 
(see [this branch](https://github.com/sergiofenoll/project-databases/tree/8-data-loader))

**Comment by MeyerJon** [comment]
This has been fully implemented, I believe. It's now possible to create new tables or append to existing tables when loading a single CSV file. 
There's no user interface for this yet, since I didn't know how we want this to look. 
I'm closing the issue for now, but as always, reopen it if you feel like it still needs to be worked on.
